import fs from 'fs';
import { tryUpdateDBIfNeed } from '@/db/updateDB';

export const initDB = async (db: any, sqliteDBPath: any) => {
    if (!fs.existsSync(sqliteDBPath) || fs.statSync(sqliteDBPath).size === 0) {
        await initTable(db);
    }
    await tryUpdateDBIfNeed(db);
};

const initTable = async (db: any) => {
    const lastLocalDBVersion = 21;
    const initSQLList = [
        `CREATE TABLE auto_sorting_chute (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT,
            chuteNo TEXT,
            chuteNoInt INTEGER,
            isEnabled INTEGER DEFAULT 1,
            chuteType TEXT,
            isException INTEGER,
            exceptionType TEXT,
            groupId INTEGER,
            sequence INTEGER DEFAULT 0,
            isDeleted INTEGER,
            assignableCondition TEXT,
            conditionValue TEXT,
            createdBy TEXT,
            createdWhen TEXT,
            updatedBy TEXT,
            updatedWhen TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT,
            CONSTRAINT uk_chute UNIQUE (platform,chuteNo)
        )`,
        `CREATE TABLE auto_sorting_chute_binding (
            chuteId INTEGER PRIMARY KEY,
            workStatus TEXT,
            jobId INTEGER,
            routeName TEXT,
            chuteKey TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE TABLE auto_sorting_config (
            key TEXT PRIMARY KEY,
            value TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `insert into auto_sorting_config (key,value) values("local_db_ver", ${lastLocalDBVersion})`,
        `CREATE TABLE auto_sorting_wave (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL,
            waveNo TEXT NOT NULL,
            status TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT,
            CONSTRAINT uk_wave UNIQUE (platform, waveNo)
        )`,
        `CREATE TABLE auto_sorting_job_item (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            waveId INTEGER NOT NULL,
            waveNo TEXT,
            jobId INTEGER NOT NULL,
            chuteKey TEXT,
            itemId TEXT,
            itemName TEXT,
            barcode TEXT,
            shipToAddress TEXT,
            weight NUMERIC,
            volume NUMERIC,
            length NUMERIC,
            height NUMERIC,
            width NUMERIC,
            cubicFeet NUMERIC,
            packageType TEXT,
            zipcode TEXT,
            qty NUMERIC,
            assignedQty NUMERIC,
            status TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_item_waveId ON auto_sorting_job_item(waveId)`,
        `CREATE INDEX idx_item_jobId ON auto_sorting_job_item(jobId)`,
        `CREATE INDEX idx_item_chuteKey ON auto_sorting_job_item(chuteKey)`,
        `CREATE TABLE auto_sorting_chute_detail (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            waveId integer,
            chuteId integer,
            jobId integer,
            jobItemId integer,
            waveNo TEXT,
            platform TEXT,
            chuteNo TEXT,
            chuteKey TEXT,
            routeName TEXT,
            itemId TEXT,
            itemName TEXT,
            barcode TEXT,
            businessStrategyId INTEGER,
            strategyName TEXT,
            strategyType TEXT,
            status TEXT,
            taskId TEXT,
            scanNo TEXT,
            departTime BIGINT,
            agvNo TEXT,
            agvUnloadTime BIGINT,
            qty NUMERIC,
            weight NUMERIC,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT,
            event_date TEXT
        )`,
        `CREATE INDEX idx_chute_detail ON auto_sorting_chute_detail(platform,chuteNo)`,
        `CREATE INDEX idx_detail_platform_chuteKey ON auto_sorting_chute_detail(platform,chuteKey)`,
        `CREATE INDEX idx_detail_platform_routeName ON auto_sorting_chute_detail(platform,routeName)`,
        `CREATE TABLE auto_sorting_chute_detail_history (
            chuteDetailId INTEGER ,
            waveId integer,
            chuteId integer,
            jobId integer,
            jobItemId integer,
            waveNo TEXT,
            platform TEXT,
            chuteNo TEXT,
            chuteKey TEXT,
            routeName TEXT,
            itemId TEXT,
            itemName TEXT,
            barcode TEXT,
            businessStrategyId INTEGER,
            strategyName TEXT,
            strategyType TEXT,
            status TEXT,
            taskId TEXT,
            scanNo TEXT,
            departTime BIGINT,
            agvNo TEXT,
            agvUnloadTime BIGINT,
            qty NUMERIC,
            weight NUMERIC,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT,
            event_date TEXT,
            operationType TEXT,
            operationTime TEXT
        )`,
        `CREATE INDEX idx_history_chuteDetailId ON auto_sorting_chute_detail_history(chuteDetailId)`,
        `CREATE INDEX idx_history_platform_chuteNo ON auto_sorting_chute_detail_history(platform,chuteNo)`,
        `CREATE INDEX idx_history_platform_chuteKey ON auto_sorting_chute_detail_history(platform,chuteKey)`,
        `CREATE INDEX idx_history_platform_routeName ON auto_sorting_chute_detail_history(platform,routeName)`,
        `CREATE TABLE auto_sorting_package (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT,
            packageType TEXT,
            waveNo TEXT,
            chuteNo TEXT,
            chuteKey TEXT,
            packageNo TEXT,
            packageTime BIGINT,
            isFromReport INTEGER,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_package ON auto_sorting_package(platform,chuteKey)`,
        `CREATE TABLE auto_sorting_package_detail (
            packageId INTEGER,
            chuteDetailId INTEGER,
            barcode TEXT,
            qty NUMERIC
        )`,
        `CREATE INDEX idx_package_detail ON auto_sorting_package_detail(packageId)`,
        `CREATE TABLE  auto_sorting_job (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            waveId INTEGER,
            waveNo TEXT,
            chuteKey TEXT,
            terminal TEXT,
            chuteId INTEGER,
            chuteNo TEXT,
            chuteNos TEXT,
            parentChuteNo TEXT,
            chuteNosHistory TEXT,
            jobQty NUMERIC,
            sortedQty NUMERIC DEFAULT 0,
            status TEXT,
            completeDate TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
            )`,
        `CREATE INDEX idx_job_waveId ON auto_sorting_job(waveId)`,
        `CREATE INDEX idx_job_chuteId ON auto_sorting_job(chuteId)`,
        `CREATE INDEX idx_job_chuteNo ON auto_sorting_job(chuteNo)`,
        `CREATE INDEX idx_job_completeDate ON auto_sorting_job(completeDate)`,
        `CREATE INDEX idx_job_chuteKey ON auto_sorting_job(chuteKey)`,
        `CREATE INDEX idx_job_terminal ON auto_sorting_job(terminal)`,
        `CREATE TABLE  auto_sorting_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL,
            logType TEXT,
            logName TEXT,
            message TEXT,
            isException INTEGER,
            data TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now'))
            )`,
        `CREATE INDEX idx_log_platform ON auto_sorting_log(platform)`,
        `CREATE INDEX idx_log_platform_logType ON auto_sorting_log(platform, logType)`,
        `CREATE INDEX idx_log_platform_isException ON auto_sorting_log(platform, isException)`,
        `CREATE INDEX idx_log_platform_logType_isException ON auto_sorting_log(platform, logType,isException)`,
        `CREATE INDEX idx_log_platform_createdAt ON auto_sorting_log(platform, createdAt)`,
        `CREATE TABLE auto_sorting_user_strategy (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            strategyName TEXT NOT NULL,
            parameters TEXT,
            strategyType TEXT,
            description TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
            )`,
        `CREATE INDEX idx_user_strategy_strategyName ON auto_sorting_user_strategy(strategyName)`,
        `CREATE TABLE auto_sorting_business_strategy (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business TEXT NOT NULL,
            userStrategyId INTEGER,
            isEnabled INTEGER DEFAULT 1,
            priority INTEGER,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
            )`,
        `CREATE INDEX idx_business_strategy ON auto_sorting_business_strategy(business)`,
        `CREATE TABLE auto_sorting_group (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL,
            groupName TEXT NOT NULL,
            isEnabled INTEGER DEFAULT 1,
            dropOffPoints TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
            )`,
        `CREATE INDEX idx_group_platform ON auto_sorting_group(platform)`,
        `CREATE TABLE auto_sorting_packages_monitor (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            trackingNo TEXT,
            platform TEXT NOT NULL,
            status TEXT,
            terminal TEXT,
            waveNo TEXT,
            routeNo TEXT,
            chuteNo TEXT,
            label_Code TEXT,
            exceptionReason TEXT,
            createTime TEXT,
            updateTime TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_packages_monitor_platform ON auto_sorting_packages_monitor(platform)`,
        `CREATE INDEX idx_packages_monitor_platform_trackingNo ON auto_sorting_packages_monitor(platform,trackingNo)`,
        `CREATE INDEX idx_packages_monitor_platform_waveNo ON auto_sorting_packages_monitor(platform,waveNo)`,
        `CREATE INDEX idx_packages_monitor_platform_terminal ON auto_sorting_packages_monitor(platform,terminal)`,
        `CREATE INDEX idx_packages_monitor_platform_routeNo ON auto_sorting_packages_monitor(platform,routeNo)`,
        `CREATE INDEX idx_packages_monitor_platform_chuteNo ON auto_sorting_packages_monitor(platform,chuteNo)`,
        `CREATE TABLE auto_sorting_chute_allocation (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT,
            routeName TEXT NOT NULL,
            type TEXT,
            isChuteNeeded INTEGER,
            fixedChuteNos TEXT,
            createdWhen TEXT,
            updatedWhen TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_chute_allocation_platform ON auto_sorting_chute_allocation(platform)`,
        `CREATE INDEX idx_chute_allocation_platform_routeName ON auto_sorting_chute_allocation(platform,routeName)`,
        `CREATE TABLE auto_sorting_queue (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT,
            data TEXT,
            platform TEXT,
            config TEXT,
            type TEXT,
            createdWhen TEXT,
            updatedWhen TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_queue_platform_type ON auto_sorting_queue(platform,type)`,
        `CREATE TABLE auto_sorting_label (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            tag TEXT,
            curId NUMERIC,
            platform TEXT,
            createdWhen TEXT,
            updatedWhen TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_label_platform_tag ON auto_sorting_label(platform,tag)`,
        `CREATE TABLE auto_sorting_package_data_pool_today (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT,
            pickupDate TEXT,
            routeName TEXT,
            count NUMERIC,
            packageType TEXT,
            createdWhen TEXT,
            updatedWhen TEXT,
            createdAt BIGINT DEFAULT (strftime('%s', 'now')),
            updatedAt BIGINT
        )`,
        `CREATE INDEX idx_package_data_pool_today_platform_pickupDate ON auto_sorting_package_data_pool_today(platform, pickupDate)`,
        `CREATE INDEX idx_package_data_pool_today_platform_routeName ON auto_sorting_package_data_pool_today(platform, routeName)`,
        `CREATE INDEX idx_package_data_pool_today_platform_packageType ON auto_sorting_package_data_pool_today(platform, packageType)`,
    ];
    await db.runBySqlArray(db, initSQLList);
};
